import Foundation

/// Writes human/LLM-readable onboarding docs into the vault *root* so coding agents
/// (Claude Code, Cursor, Codex, …) that open the folder immediately understand it is an
/// HTMLGraph vault and follow its conventions — instead of treating the bare, hidden
/// `.htmlgraph/` sidecar as an inscrutable blob and guessing what to do.
///
/// Two files are written at the vault root (not inside `.htmlgraph/`) because that is
/// where agents auto-discover instructions:
/// - `AGENTS.md` — the full guide; the cross-tool open standard read by Cursor, Codex,
///   Copilot, Zed, and recent Claude Code.
/// - `CLAUDE.md` — a thin pointer that imports `AGENTS.md` (`@AGENTS.md`), so Claude
///   Code, which reads `CLAUDE.md` by default, picks up the same single source of truth.
///
/// Both files are plain `.md`, so `VaultIndexer` (which only ingests `.html`/`.htm` and
/// skips hidden files) never indexes them — there is no feedback loop into the graph.
///
/// Policy: **create-only**. ``writeIfMissing(vaultURL:)`` never overwrites an existing
/// file, so user edits — and the read-only-vault expectation — are preserved across the
/// reindexes that happen on every document change. A deliberate refresh is a separate,
/// explicit action: ``regenerate(vaultURL:)``, surfaced in the app as a menu command.
public struct VaultAgentGuideWriter {
    public static let agentsFileName = "AGENTS.md"
    public static let claudeFileName = "CLAUDE.md"

    public init() {}

    /// Location of the full agent guide for a given vault.
    public static func agentsFileURL(forVault vaultURL: URL) -> URL {
        vaultURL.appendingPathComponent(agentsFileName)
    }

    /// Location of the Claude Code pointer file for a given vault.
    public static func claudeFileURL(forVault vaultURL: URL) -> URL {
        vaultURL.appendingPathComponent(claudeFileName)
    }

    /// Describes which guide files a call actually wrote, so callers can log or surface it.
    public struct Outcome: Equatable, Sendable {
        public var wroteAgents: Bool
        public var wroteClaude: Bool

        public init(wroteAgents: Bool, wroteClaude: Bool) {
            self.wroteAgents = wroteAgents
            self.wroteClaude = wroteClaude
        }

        /// True when at least one file was (re)written.
        public var createdAny: Bool { wroteAgents || wroteClaude }
    }

    /// Create-only: writes each guide file only when it is missing. Existing files —
    /// whether the user customised them or wrote their own — are left untouched. The two
    /// files are handled independently, so a vault that already has, say, a hand-written
    /// `CLAUDE.md` still gets an `AGENTS.md`.
    @discardableResult
    public func writeIfMissing(vaultURL: URL) throws -> Outcome {
        Outcome(
            wroteAgents: try Self.createOnly(Self.agentsGuide, at: Self.agentsFileURL(forVault: vaultURL)),
            wroteClaude: try Self.createOnly(Self.claudePointer, at: Self.claudeFileURL(forVault: vaultURL))
        )
    }

    /// Writes `contents` only when nothing exists at `url`; returns whether it created the
    /// file. Uses `.withoutOverwriting` instead of a `fileExists` pre-check so the
    /// create-only guarantee has no time-of-check/time-of-use race — the write itself
    /// fails (leaving any existing file untouched) when a file is already there, which we
    /// translate to "skipped". Other write errors propagate to the best-effort caller.
    private static func createOnly(_ contents: String, at url: URL) throws -> Bool {
        do {
            try Data(contents.utf8).write(to: url, options: .withoutOverwriting)
            return true
        } catch let error as CocoaError where error.code == .fileWriteFileExists {
            return false
        }
    }

    /// Force-overwrites both guide files with the current templates — the "Regenerate"
    /// action. Destructive to manual edits, so the UI confirms before calling this.
    @discardableResult
    public func regenerate(vaultURL: URL) throws -> Outcome {
        try Self.agentsGuide.write(
            to: Self.agentsFileURL(forVault: vaultURL), atomically: true, encoding: .utf8)
        try Self.claudePointer.write(
            to: Self.claudeFileURL(forVault: vaultURL), atomically: true, encoding: .utf8)
        return Outcome(wroteAgents: true, wroteClaude: true)
    }

    // MARK: - Templates

    /// The full guide. Kept deterministic (no timestamps/counts) so repeated regeneration
    /// produces byte-identical output and diffs stay clean.
    static let agentsGuide = """
        # Working in this HTMLGraph vault

        > Auto-generated by the HTMLGraph app to orient AI coding agents (Claude Code,
        > Cursor, Codex, …) that open this folder. HTMLGraph will **not** overwrite this
        > file once it exists — edit it freely. To restore the default, run
        > **File ▸ Regenerate Agent Guide** in the HTMLGraph app.

        ## What this folder is

        This is an **HTMLGraph vault**: a local, interlinked knowledge base made of plain
        **HTML files**. Think of it as an Obsidian vault where the notes are HTML
        (`.html` / `.htm`) instead of Markdown and links are ordinary `<a href>` tags. The
        HTMLGraph macOS app indexes these files into a graph — each document is a node,
        each link is an edge — and shows backlinks, local/global graph views, and
        on-device semantic search.

        When asked to add or change notes here, your goal is to **write well-formed HTML
        notes that link to each other**, so the graph stays rich and navigable.

        ## Layout

        ```
        <vault>/
        ├── *.html / *.htm     ← notes (each file is one graph node); may be nested in folders
        ├── AGENTS.md          ← this guide
        ├── CLAUDE.md          ← points Claude Code at AGENTS.md
        ├── Inbox/             ← drop NEW, unfiled notes here for the user to review
        └── .htmlgraph/        ← machine-generated; DO NOT edit by hand
            ├── graph.json     ← the computed graph (read this to understand structure)
            └── embeddings.json ← semantic-search vectors
        ```

        ## Authoring rules

        1. **One note = one HTML file.** Use the `.html` extension and UTF-8 encoding.
        2. **Give every note a title.** The app derives a node's title from `<title>`,
           falling back to the first `<h1>`, then the filename. Always set both a
           `<title>` and an `<h1>`.
        3. **Link with relative, vault-local paths.** Connect notes with
           `<a href="./other-note.html">…</a>` (or `../folder/note.html`). Relative hrefs
           that point at real files in the vault become graph **edges** and create
           **backlinks** on the target automatically.
        4. **Don't create broken links.** A relative href to a file that doesn't exist is
           recorded as an *unresolved* (broken) link. Either create the target note or fix
           the href.
        5. **External links** (`http(s)://`, `mailto:`) are kept as external edges — fine
           to use, but they are not graph nodes.
        6. **Fragments** like `<a href="./note.html#section">` are supported; an in-page
           `#anchor` link is treated as a same-document link.
        7. **Static HTML only.** Vaults open in **Safe mode** by default: **no JavaScript,
           no network access**. Don't rely on JS to render content or fetch remote
           resources. Keep CSS and images inside the vault and reference them relatively.

        ## Adding new notes → use `Inbox/`

        If you are generating a *new* note the user hasn't explicitly placed, write it into
        **`Inbox/`** (create the folder if needed). HTMLGraph surfaces Inbox items so the
        user can review them and file them into the vault. When the user asks you to edit
        an *existing* note, edit it in place instead — don't duplicate it into `Inbox/`.

        ## Reading the graph — `.htmlgraph/graph.json`

        `graph.json` is the source of truth for structure. Read it instead of re-parsing
        every HTML file. Shape (`schemaVersion: 1`):

        - `documents[]` — `{ id, path, absolutePath, title, contentHash, lastModified }`.
          `id`/`path` are vault-relative (e.g. `notes/graph.html`).
        - `edges[]` — `{ id, sourceId, targetId, href, linkText, status, fragment, … }`.
          `status` is one of `resolved | unresolved | sameDocument | external`.
        - `backlinks` — map of `targetId → edges[]` (what links *to* a note).
        - `unresolvedLinks` — map of `sourceId → edges[]` (broken links worth fixing).

        Use it to answer "what links here?", "what's orphaned?", or "what's broken?" — then
        make your edits in the HTML.

        **Never edit anything under `.htmlgraph/`.** HTMLGraph regenerates that directory on
        every index, so manual changes are lost and can confuse the app. Read it; don't
        write it.
        """

    /// The Claude Code pointer. `@AGENTS.md` is Claude Code's import syntax, so the full
    /// guide is pulled in without duplicating its content.
    static let claudePointer = """
        # CLAUDE.md

        This folder is an **HTMLGraph vault**. The full agent guide — vault layout, how to
        author HTML notes, linking rules, and how to read `.htmlgraph/graph.json` — lives in
        **AGENTS.md**. Read and follow it.

        @AGENTS.md
        """
}
